name: sample
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: Multi line script
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: current directory
        run: Get-Location
      - name: current Location
        run: pwd
        shell: bash